spec_root: &spec_root
  x-modules:
    - spec:
        info:
          version: 1.0.0-beta
          title: ServiceWorker render proxy service
          description: >
            Server-side ServiceWorker execution for pre-rendering &
            support of clients without ServiceWorker support.

          termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
          contact:
            name: the Wikimedia Services team
            url: http://mediawiki.org/wiki/Wikimedia_Services
          license:
            name: Apache2
            url: http://www.apache.org/licenses/LICENSE-2.0
        x-sub-request-filters:
          - type: default
            name: http
            options:
              allow:
                - pattern: /^https?:\/\//
        x-modules:
          - path: ./v1/sw_proxy.js
            options:
              # TODO: Restrict default domains with a regexp
              # default_domain_pattern: \\.(?:wikipedia.org)$
              domain_defaults:
                scriptURL: /_sw.js
                # Override for cache-control; todo: use s-maxage from sw
                # response?
                # - parse cache-control in response
                # - use s-maxage for server side, fall back to default
                # - send supplied max-age to client, fall back to config
                # default
                sw_default_cache_control:
                    max-age: 3600
                    s-maxage: 300
                # Per-domain config / overrides
              domains:
                en.wikipedia.org:
                  scriptURL: https://raw.githubusercontent.com/gwicke/streaming-serviceworker-playground/master/build/sw.js

# Finally, a standard service-runner config.
services:
  - name: serviceworker-proxy
    module: hyperswitch
    conf: 
      port: 8934
      spec: *spec_root
      salt: secret
      user_agent: ServiceWorker Proxy

logging:
  level: info
  #streams:
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>

metrics:
  type: statsd
  host: localhost
  port: 8125
  batch: true

ratelimiter:
  type: kademlia
  # Cluster nodes
  seeds:
    # Port 3050 used by default
    - 127.0.0.1
